server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  application:
    name: customer

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_db
    username: tanarak wongkitikun
    password: Scb1234!

  security:
    user:
      name: T
      password: 1234
      roles: admin